-- =========================================
-- PACIENTES
-- =========================================
INSERT INTO PACIENTE (ID_PACIENTE, NOMBRE, APELLIDO, DNI, FECHA_NACIMIENTO, DIRECCION, TELEFONO)
VALUES (seq_paciente.NEXTVAL, 'Ana', 'Torres', '12345678', TO_DATE('1990-05-12','YYYY-MM-DD'), 'Av. Lima 123', '987654321');

INSERT INTO PACIENTE (ID_PACIENTE, NOMBRE, APELLIDO, DNI, FECHA_NACIMIENTO, DIRECCION, TELEFONO)
VALUES (seq_paciente.NEXTVAL, 'Luis', 'Garcia', '87654321', TO_DATE('1985-08-20','YYYY-MM-DD'), 'Jr. Arequipa 456', '987654322');

INSERT INTO PACIENTE (ID_PACIENTE, NOMBRE, APELLIDO, DNI, FECHA_NACIMIENTO, DIRECCION, TELEFONO)
VALUES (seq_paciente.NEXTVAL, 'Maria', 'Lopez', '11223344', TO_DATE('1992-03-15','YYYY-MM-DD'), 'Av. Grau 789', '987654323');

INSERT INTO PACIENTE (ID_PACIENTE, NOMBRE, APELLIDO, DNI, FECHA_NACIMIENTO, DIRECCION, TELEFONO)
VALUES (seq_paciente.NEXTVAL, 'Carlos', 'Perez', '44332211', TO_DATE('1980-11-01','YYYY-MM-DD'), 'Jr. Callao 101', '987654324');

-- =========================================
-- MEDICOS
-- =========================================
INSERT INTO MEDICO (ID_MEDICO, NOMBRE, APELLIDO, ESPECIALIDAD, TELEFONO)
VALUES (seq_medico.NEXTVAL, 'Dr. Juan', 'Ramirez', 'Cardiología', '987111111');

INSERT INTO MEDICO (ID_MEDICO, NOMBRE, APELLIDO, ESPECIALIDAD, TELEFONO)
VALUES (seq_medico.NEXTVAL, 'Dra. Sofia', 'Mendoza', 'Pediatría', '987222222');

INSERT INTO MEDICO (ID_MEDICO, NOMBRE, APELLIDO, ESPECIALIDAD, TELEFONO)
VALUES (seq_medico.NEXTVAL, 'Dr. Alberto', 'Vargas', 'Neurología', '987333333');

-- =========================================
-- MEDICAMENTOS
-- =========================================
INSERT INTO MEDICAMENTO (ID_MEDICAMENTO, NOMBRE, STOCK, PRECIO)
VALUES (seq_medicamento.NEXTVAL, 'Paracetamol', 100, 5.50);

INSERT INTO MEDICAMENTO (ID_MEDICAMENTO, NOMBRE, STOCK, PRECIO)
VALUES (seq_medicamento.NEXTVAL, 'Ibuprofeno', 50, 8.75);

INSERT INTO MEDICAMENTO (ID_MEDICAMENTO, NOMBRE, STOCK, PRECIO)
VALUES (seq_medicamento.NEXTVAL, 'Amoxicilina', 200, 12.00);

-- =========================================
-- CITAS
-- =========================================
-- Supongamos que los IDs generados de pacientes son 1-4 y médicos 1-3
INSERT INTO CITA (ID_CITA, ID_PACIENTE, ID_MEDICO, FECHA, HORA, ESTADO)
VALUES (seq_cita.NEXTVAL, 1, 1, TO_DATE('2025-10-01','YYYY-MM-DD'), '09:00', 'Pendiente');

INSERT INTO CITA (ID_CITA, ID_PACIENTE, ID_MEDICO, FECHA, HORA, ESTADO)
VALUES (seq_cita.NEXTVAL, 2, 2, TO_DATE('2025-10-02','YYYY-MM-DD'), '10:30', 'Confirmada');

INSERT INTO CITA (ID_CITA, ID_PACIENTE, ID_MEDICO, FECHA, HORA, ESTADO)
VALUES (seq_cita.NEXTVAL, 3, 3, TO_DATE('2025-10-03','YYYY-MM-DD'), '14:00', 'Cancelada');

INSERT INTO CITA (ID_CITA, ID_PACIENTE, ID_MEDICO, FECHA, HORA, ESTADO)
VALUES (seq_cita.NEXTVAL, 4, 1, TO_DATE('2025-10-04','YYYY-MM-DD'), '11:15', 'Pendiente');

-- =========================================
-- FACTURAS
-- =========================================
INSERT INTO FACTURA (ID_FACTURA, ID_PACIENTE, MONTO, FECHA, ESTADO)
VALUES (seq_factura.NEXTVAL, 1, 150.00, TO_DATE('2025-10-01','YYYY-MM-DD'), 'Pagada');

INSERT INTO FACTURA (ID_FACTURA, ID_PACIENTE, MONTO, FECHA, ESTADO)
VALUES (seq_factura.NEXTVAL, 2, 200.50, TO_DATE('2025-10-02','YYYY-MM-DD'), 'Pendiente');

INSERT INTO FACTURA (ID_FACTURA, ID_PACIENTE, MONTO, FECHA, ESTADO)
VALUES (seq_factura.NEXTVAL, 3, 75.00, TO_DATE('2025-10-03','YYYY-MM-DD'), 'Pagada');

-- =========================================
-- HOSPITALIZACIONES
-- =========================================
INSERT INTO HOSPITALIZACION (ID_HOSPITALIZACION, ID_PACIENTE, HABITACION, FECHA_INGRESO, FECHA_ALTA)
VALUES (seq_hospitalizacion.NEXTVAL, 1, '101A', TO_DATE('2025-09-28','YYYY-MM-DD'), TO_DATE('2025-10-02','YYYY-MM-DD'));

INSERT INTO HOSPITALIZACION (ID_HOSPITALIZACION, ID_PACIENTE, HABITACION, FECHA_INGRESO, FECHA_ALTA)
VALUES (seq_hospitalizacion.NEXTVAL, 2, '102B', TO_DATE('2025-09-29','YYYY-MM-DD'), NULL);

INSERT INTO HOSPITALIZACION (ID_HOSPITALIZACION, ID_PACIENTE, HABITACION, FECHA_INGRESO, FECHA_ALTA)
VALUES (seq_hospitalizacion.NEXTVAL, 3, '103C', TO_DATE('2025-09-30','YYYY-MM-DD'), TO_DATE('2025-10-03','YYYY-MM-DD'));
