CREATE SEQUENCE seq_paciente START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_medico START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_cita START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_medicamento START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_factura START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_hospitalizacion START WITH 1 INCREMENT BY 1;

CREATE TABLE PACIENTE (
    ID_PACIENTE NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(100) NOT NULL,
    APELLIDO VARCHAR2(100) NOT NULL,
    DNI VARCHAR2(15) UNIQUE NOT NULL,
    FECHA_NACIMIENTO DATE,
    DIRECCION VARCHAR2(200),
    TELEFONO VARCHAR2(20)
);

CREATE UNIQUE INDEX idx_paciente_dni ON PACIENTE(DNI);
CREATE INDEX idx_paciente_apellido ON PACIENTE(APELLIDO);

CREATE TABLE MEDICO (
    ID_MEDICO NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(100) NOT NULL,
    APELLIDO VARCHAR2(100) NOT NULL,
    ESPECIALIDAD VARCHAR2(100),
    TELEFONO VARCHAR2(20)
);

CREATE INDEX idx_medico_especialidad ON MEDICO(ESPECIALIDAD);

CREATE TABLE CITA (
    ID_CITA NUMBER PRIMARY KEY,
    ID_PACIENTE NUMBER NOT NULL,
    ID_MEDICO NUMBER,
    FECHA DATE NOT NULL,
    HORA VARCHAR2(10),
    ESTADO VARCHAR2(20) DEFAULT 'Pendiente' CHECK (ESTADO IN ('Pendiente','Confirmada','Cancelada')),
    CONSTRAINT fk_cita_paciente FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTE(ID_PACIENTE) ON DELETE CASCADE,
    CONSTRAINT fk_cita_medico FOREIGN KEY (ID_MEDICO) REFERENCES MEDICO(ID_MEDICO) ON DELETE SET NULL
);

CREATE INDEX idx_cita_paciente ON CITA(ID_PACIENTE);
CREATE INDEX idx_cita_medico ON CITA(ID_MEDICO);
CREATE INDEX idx_cita_fecha ON CITA(FECHA);

CREATE TABLE MEDICAMENTO (
    ID_MEDICAMENTO NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(100) NOT NULL,
    STOCK NUMBER DEFAULT 0,
    PRECIO NUMBER(10,2) DEFAULT 0
);

CREATE INDEX idx_medicamento_nombre ON MEDICAMENTO(NOMBRE);

CREATE TABLE FACTURA (
    ID_FACTURA NUMBER PRIMARY KEY,
    ID_PACIENTE NUMBER NOT NULL,
    MONTO NUMBER(10,2) DEFAULT 0,
    FECHA DATE DEFAULT SYSDATE,
    ESTADO VARCHAR2(20) DEFAULT 'Pendiente' CHECK (ESTADO IN ('Pendiente','Pagada')),
    CONSTRAINT fk_factura_paciente FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTE(ID_PACIENTE) ON DELETE CASCADE
);

CREATE INDEX idx_factura_paciente ON FACTURA(ID_PACIENTE);
CREATE INDEX idx_factura_fecha ON FACTURA(FECHA);

CREATE TABLE HOSPITALIZACION (
    ID_HOSPITALIZACION NUMBER PRIMARY KEY,
    ID_PACIENTE NUMBER NOT NULL,
    HABITACION VARCHAR2(10),
    FECHA_INGRESO DATE NOT NULL,
    FECHA_ALTA DATE,
    CONSTRAINT fk_hosp_paciente FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTE(ID_PACIENTE) ON DELETE CASCADE
);

CREATE INDEX idx_hosp_paciente ON HOSPITALIZACION(ID_PACIENTE);
CREATE INDEX idx_hosp_fecha_ingreso ON HOSPITALIZACION(FECHA_INGRESO);
