-- Pacientes
CREATE TABLE PACIENTE (
    ID_PACIENTE NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(100),
    APELLIDO VARCHAR2(100),
    DNI VARCHAR2(15) UNIQUE,
    FECHA_NACIMIENTO DATE,
    DIRECCION VARCHAR2(200),
    TELEFONO VARCHAR2(20)
);

-- Médicos
CREATE TABLE MEDICO (
    ID_MEDICO NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(100),
    APELLIDO VARCHAR2(100),
    ESPECIALIDAD VARCHAR2(100),
    TELEFONO VARCHAR2(20)
);

-- Citas
CREATE TABLE CITA (
    ID_CITA NUMBER PRIMARY KEY,
    ID_PACIENTE NUMBER REFERENCES PACIENTE(ID_PACIENTE),
    ID_MEDICO NUMBER REFERENCES MEDICO(ID_MEDICO),
    FECHA DATE,
    HORA VARCHAR2(10),
    ESTADO VARCHAR2(20)
);

-- Medicamentos (Farmacia)
CREATE TABLE MEDICAMENTO (
    ID_MEDICAMENTO NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(100),
    STOCK NUMBER,
    PRECIO NUMBER(10,2)
);

-- Facturación
CREATE TABLE FACTURA (
    ID_FACTURA NUMBER PRIMARY KEY,
    ID_PACIENTE NUMBER REFERENCES PACIENTE(ID_PACIENTE),
    MONTO NUMBER(10,2),
    FECHA DATE,
    ESTADO VARCHAR2(20)
);

-- Hospitalización (Opcional)
CREATE TABLE HOSPITALIZACION (
    ID_HOSPITALIZACION NUMBER PRIMARY KEY,
    ID_PACIENTE NUMBER REFERENCES PACIENTE(ID_PACIENTE),
    HABITACION VARCHAR2(10),
    FECHA_INGRESO DATE,
    FECHA_ALTA DATE
);
